export default {
  $schema: './node_modules/oxfmt/configuration_schema.json',
  arrowParens: 'always',
  bracketSpacing: true,
  ignorePatterns: [
    '**/.adonisjs/**',
    '**/build/**',
    '**/public/assets/**',
    'types/db.ts',
    'inertia/components/ui/**',
    'tools/oxlint/anti-slop/**',
  ],
  printWidth: 100,
  quoteProps: 'consistent',
  semi: false,
  singleQuote: true,
  sortImports: {
    groups: [
      'side_effect',
      'builtin',
      'external',
      'internal',
      'parent',
      'sibling',
      'index',
      'type',
      'unknown',
    ],
    internalPattern: ['#', '~/', '@generated'],
    newlinesBetween: false,
    order: 'asc',
  },
  sortPackageJson: false,
  trailingComma: 'es5',
  useTabs: false,
}
