/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  token_hash: string;
  user_id: string;
}

export interface Ingredients {
  category: string;
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  quantity: number;
  state: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  token_hash: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: string;
  name: string | null;
  password: string;
  updated_at: Timestamp | null;
}

export interface DB {
  email_verification_tokens: EmailVerificationTokens;
  ingredients: Ingredients;
  password_reset_tokens: PasswordResetTokens;
  users: Users;
}
