/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  identity: {
    Account: () => import('#app/identity/controllers/account_controller'),
    ChangePassword: () => import('#app/identity/controllers/change_password_controller'),
    DeleteAccount: () => import('#app/identity/controllers/delete_account_controller'),
    EmailVerification: () => import('#app/identity/controllers/email_verification_controller'),
    ForgotPassword: () => import('#app/identity/controllers/forgot_password_controller'),
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    RegisterUser: () => import('#app/identity/controllers/register_user_controller'),
    RequestEmailChange: () => import('#app/identity/controllers/request_email_change_controller'),
    ResetPassword: () => import('#app/identity/controllers/reset_password_controller'),
    UpdateProfile: () => import('#app/identity/controllers/update_profile_controller'),
    VerifyEmail: () => import('#app/identity/controllers/verify_email_controller'),
  },
  inventory: {
    AddIngredient: () => import('#app/inventory/controllers/add_ingredient_controller'),
    AdjustIngredientQuantity: () => import('#app/inventory/controllers/adjust_ingredient_quantity_controller'),
    ExportInventory: () => import('#app/inventory/controllers/export_inventory_controller'),
    ImportInventory: () => import('#app/inventory/controllers/import_inventory_controller'),
    Inventory: () => import('#app/inventory/controllers/inventory_controller'),
    RemoveIngredient: () => import('#app/inventory/controllers/remove_ingredient_controller'),
    UpdateIngredient: () => import('#app/inventory/controllers/update_ingredient_controller'),
  },
  shared: {
    HealthChecks: () => import('#app/shared/controllers/health_checks_controller'),
  },
}
