/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type CookingCookingSessionTransformer from '#app/cooking/transformers/cooking_session_transformer'
import type IdentityAccountDetailsTransformer from '#app/identity/transformers/account_details_transformer'
import type IdentityMcpTokenTransformer from '#app/identity/transformers/mcp_token_transformer'
import type IdentityUserTransformer from '#app/identity/transformers/user_transformer'
import type InventoryIngredientTransformer from '#app/inventory/transformers/ingredient_transformer'
import type RecipesRecipeSummaryTransformer from '#app/recipes/transformers/recipe_summary_transformer'
import type RecipesRecipeTransformer from '#app/recipes/transformers/recipe_transformer'
import type InertiaMiddleware from '#app/middleware/inertia_middleware'

export namespace Data {
  export namespace Cooking {
    export type CookingSession = InferData<CookingCookingSessionTransformer>
    export namespace CookingSession {
      export type Variants = InferVariants<CookingCookingSessionTransformer>
    }
  }
  export namespace Identity {
    export type AccountDetails = InferData<IdentityAccountDetailsTransformer>
    export namespace AccountDetails {
      export type Variants = InferVariants<IdentityAccountDetailsTransformer>
    }
    export type McpToken = InferData<IdentityMcpTokenTransformer>
    export namespace McpToken {
      export type Variants = InferVariants<IdentityMcpTokenTransformer>
    }
    export type User = InferData<IdentityUserTransformer>
    export namespace User {
      export type Variants = InferVariants<IdentityUserTransformer>
    }
  }
  export namespace Inventory {
    export type Ingredient = InferData<InventoryIngredientTransformer>
    export namespace Ingredient {
      export type Variants = InferVariants<InventoryIngredientTransformer>
    }
  }
  export namespace Recipes {
    export type RecipeSummary = InferData<RecipesRecipeSummaryTransformer>
    export namespace RecipeSummary {
      export type Variants = InferVariants<RecipesRecipeSummaryTransformer>
    }
    export type Recipe = InferData<RecipesRecipeTransformer>
    export namespace Recipe {
      export type Variants = InferVariants<RecipesRecipeTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
